apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geoserver.fullname" . }}-gateway
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  {{- if or .Values.global.annotations .Values.geoserver.gateway.annotations }}
  annotations:
    {{- if .Values.global.annotations }}
    {{- toYaml .Values.global.annotations | nindent 4 }}
    {{- end -}}
    {{- if .Values.geoserver.gateway.annotations }}
    {{- toYaml .Values.geoserver.gateway.annotations | nindent 4 }}
    {{- end -}}
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit | default 3 }}
  replicas: {{ .Values.geoserver.gateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "geoserver.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  template:
    metadata:
      annotations:
      {{- with .Values.geoserver.gateway.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/config/configmap.yaml") . | sha256sum }}
        specificValues/sha256: {{ toYaml .Values.geoserver.gateway | sha256sum }}
        globalValues/sha256: {{ toYaml .Values.global | sha256sum }}
      labels:
        {{- include "geoserver.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: gateway
        {{- if .Values.global.custom_pod_labels }}
          {{- toYaml .Values.global.custom_pod_labels | nindent 8 }}
        {{- end }}
    spec:
      volumes:
        # we define an emptyDir that can be used by optional initContainers if needed
        - name: localshare
          emptyDir: {}
        - name: configs
          configMap:
            name: {{ include "geoserver.fullname" . }}-config-configs
      {{- if or .Values.geoserver.custom.commonInitContainers .Values.geoserver.gateway.initContainers }}
      initContainers:
      {{- if .Values.geoserver.custom.commonInitContainers }}
      {{- toYaml .Values.geoserver.custom.commonInitContainers | nindent 8 }}
      {{- end }}
      {{- if .Values.geoserver.gateway.initContainers }}
      {{- toYaml .Values.geoserver.gateway.initContainers | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if $values.global.image.registrySecretName }}
      imagePullSecrets:
        - name: {{ $values.global.image.registrySecretName }}
      {{- end }}
      serviceAccountName: {{ include "geoserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.geoserver.gateway.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-gateway
          securityContext:
            {{- toYaml .Values.geoserver.gateway.securityContext | nindent 12 }}
          image: "{{ trimSuffix "/" .Values.global.image.registry | default "docker.io" }}/{{ .Values.geoserver.gateway.image.repository }}:{{ .Values.geoserver.gateway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            - name: TARGETS_WMS
              value: http://{{ include "geoserver.fullname" . }}-wms:{{ .Values.geoserver.services.wms.service.port }}
            - name: TARGETS_WFS
              value: http://{{ include "geoserver.fullname" . }}-wfs:{{ .Values.geoserver.services.wfs.service.port }}
            - name: TARGETS_WCS
              value: http://{{ include "geoserver.fullname" . }}-wcs:{{ .Values.geoserver.services.wcs.service.port }}
            - name: TARGETS_GWC
              value: http://{{ include "geoserver.fullname" . }}-gwc:{{ .Values.geoserver.services.gwc.service.port }}
            - name: TARGETS_REST
              value: http://{{ include "geoserver.fullname" . }}-rest:{{ .Values.geoserver.services.rest.service.port }}
            - name: TARGETS_WEBUI
              value: http://{{ include "geoserver.fullname" . }}-webui:{{ .Values.geoserver.services.webui.service.port }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.global.profile | quote}}
            {{ include "geoserver.common.env.variables" . | nindent 12}}
            {{- if .Values.geoserver.gateway.env }}
            {{ toYaml .Values.geoserver.gateway.env | nindent 12 }}
            {{- end }}

          volumeMounts:
            - name: configs
              mountPath: /etc/gscloud
            - name: localshare
              mountPath: /mnt/localshare

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          {{- if eq .Values.global.legacyk8s false }}
          startupProbe:
            httpGet:
              path: /actuator/health
              port: health
            failureThreshold: 30
            periodSeconds: 10
          {{- end }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: health
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: health
            periodSeconds: 5

          resources:
            {{- toYaml .Values.geoserver.gateway.resources | nindent 12 }}
      {{- with .Values.geoserver.gateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.geoserver.gateway.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.geoserver.gateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
