apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geoserver.fullname" . }}-gateway
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  {{- if or .Values.global.annotations .Values.geoserver.gateway.annotations }}
  annotations:
    {{- if .Values.global.annotations }}
    {{- toYaml .Values.global.annotations | nindent 4 }}
    {{- end -}}
    {{- if .Values.geoserver.gateway.annotations }}
    {{- toYaml .Values.geoserver.gateway.annotations | nindent 4 }}
    {{- end -}}
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit | default 3 }}
  replicas: {{ .Values.geoserver.gateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "geoserver.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  template:
    metadata:
      annotations:
      {{- with .Values.geoserver.gateway.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/config/configmap.yaml") . | sha256sum }}
        values/sha256: {{ toYaml .Values | sha256sum }}
      labels:
        {{- include "geoserver.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: gateway
        {{- if .Values.global.custom_pod_labels }}
          {{- toYaml .Values.global.custom_pod_labels | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "geoserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.geoserver.gateway.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-gateway
          securityContext:
            {{- toYaml .Values.geoserver.gateway.securityContext | nindent 12 }}
          image: "{{ trimSuffix "/" .Values.global.image.registry | default "docker.io" }}/{{ .Values.geoserver.gateway.image.repository }}:{{ .Values.geoserver.gateway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command:

            - /bin/sh
            - -c
            - java org.springframework.boot.loader.JarLauncher
          env:
            - name: EUREKA_SERVER_URL
              value: http://{{ include "geoserver.fullname" . }}-discovery:8761/eureka
{{- if .Values.geoserver.config.env }}
{{ toYaml .Values.geoserver.config.env | indent 12 }}
{{- end }}

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 5

          resources:
            {{- toYaml .Values.geoserver.gateway.resources | nindent 12 }}
      {{- with .Values.geoserver.gateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.geoserver.gateway.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.geoserver.gateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
