{{ if eq  .Values.geoserver.ingress.deploy true }}
# apiVersion: networking.k8s.io/v1beta1 # for k3s < v1.19
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.geoserver.ingress.baseUrl }}/
        pathType: Prefix
        backend:
          service:
            name: {{ include "geoserver.fullname" . }}-gateway
            port:
              number: {{ .Values.geoserver.gateway.service.port }}
      - path: {{ .Values.geoserver.ingress.baseUrl }}/web/
        pathType: Prefix
        backend:
          service:
            name: {{ include "geoserver.fullname" . }}-webui
            port:
              number: {{ .Values.geoserver.gateway.service.port }}
      - path: {{ .Values.geoserver.ingress.baseUrl }}/discovery/
        pathType: Prefix
        backend:
          service:
            name: {{ include "geoserver.fullname" . }}-discovery
            port:
              number: {{ .Values.geoserver.gateway.discovery.port }}
{{ end }}
