# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/master/c2cciutils/schema.json

checks:
  required_workflows:
    clean.yaml: false
    audit.yaml: false
    backport.yaml: false
    codeql.yaml: false
    prettier: false
  black:
    ignore_patterns_re:
      - .*\.yaml

publish:
  helm:
    folders:
      - .
